### ISSUE TITLE
Relationship between 'clusters_xx' folders and 'original_cloud_xx.pcd' ?

### ISSUE THREAD

**Issue by PanZhichen** [PRBonn/depth_clustering#23]
When I execute './save_clusters_node ...', I got the result shown in the picture. But I don't know what the relationship between them, could you explain it for me? Very thank you for your excellent work and looking forward to your reply :)
![1](https://user-images.githubusercontent.com/23658856/38239935-c1b0f1f6-3760-11e8-98ab-01add2a20b59.png)

**Comment by niosus** [comment]
Sorry for the delay. The numbering here is consistent. I dump the clusters every 10 clouds, and `original_cloud_10` corresponds to `clusters_000010` for example. If you open them in `pcl_viewer` you should be able to see that they overlap.
