### ISSUE TITLE
thesis picture

### ISSUE THREAD

**Issue by JSRGFJZ** [PRBonn/depth_clustering#25]
Hi,  really thank you for your great work, may I know that how your draw this picture in your paper <Fast Range Image-Based Segmentation  of Sparse 3D Laser Scans for Online Operation> & <Efficient Online Segmentation for Sparse 3D Laser Scans>, now I just write some code to visulize it in rviz, but cannot have various colors. Would you like to help me
Hope to get help from you.

**Comment by niosus** [comment]
Answered in an email.
