### ISSUE TITLE
Output depth image and labeled segmented image as ros topic

### ISSUE THREAD

**Issue by tuandle** [PRBonn/depth_clustering#29]
Hi @niosus,
Thanks for open-source this package.
Please correct me if I am wrong. Looking at `show_object_ nodes`, it seems to me that an object of type `CloudOdomRosSubscriber` is the only thing initialized and subscribed to `velodyne_points` topic. 

However, it does not explicitly output any topic. I wonder if it is possible to extract depth images and labeled segmented images to `cv:Mat` type objects so that we can publish them as ros topics?

I appreciate your help!

**Comment by niosus** [comment]
Hey @tuandle,
sure it is possible, but not implemented in the framework. I currently only use ROS as a way to get the data. However, people have already done publishers that publish topics of their interest before, see #17 for the discussion about this. The publishers should be easy to implement and integrate into the pipeline. The intent of this code is to give a framework which can be forked and extended.
