### ISSUE TITLE
[fea] Simplify our beta judgement rule

### ISSUE THREAD

**Issue by yiakwy** [PRBonn/depth_clustering#35]
Hi, I have scanned through the paper and already dive into the implementation part to observe data processing flow.

I found that our beta judgment rule

![image](https://user-images.githubusercontent.com/8510840/50954870-966edd80-14f2-11e9-92ea-e937fb690672.png)

could be simplified into the following format with less numeric redundancies:

![image](https://user-images.githubusercontent.com/8510840/50954759-3d9f4500-14f2-11e9-8cb3-cb33e1c3a580.png)

Because theta should not be large and positive, this method is much better looking for your paper.

**Comment by niosus** [comment]
Thanks for your suggestion. Can you elaborate a bit more where you got this formula from? I don't see the reasoning behind it.

**Comment by niosus** [comment]
Closing for the lack of activity.
