### ISSUE TITLE
Run ./show_objects_node fail

### ISSUE THREAD

**Issue by phamquandung** [PRBonn/depth_clustering#38]
I tried to run ./show_objects_node by following this link https://wiki.nps.edu/pages/viewpage.action?pageId=925958215 (I convert the kitti raw data to bag) but the result is nothing. 
This is the process I tried to do:
First step:
![1](https://user-images.githubusercontent.com/28943896/51811599-02be4f00-22f1-11e9-8b04-f8ec95687bd3.png)
Second step:
![2](https://user-images.githubusercontent.com/28943896/51811619-208bb400-22f1-11e9-9b8c-40b6efa1ce6f.png)
Third step:
![3](https://user-images.githubusercontent.com/28943896/51811626-28e3ef00-22f1-11e9-873e-13bb27a82500.png)
And the result is:
![4](https://user-images.githubusercontent.com/28943896/51811635-339e8400-22f1-11e9-83f2-306913c97c9a.png)

Could you please help me? I really don't understand what's wrong with it because I follow the guide above.

**Comment by niosus** [comment]
I'm sorry, I won't have time to fully debug this in the near future. :( 
However, the first idea would be to check if the data is published under the topic that my code expects.

**Comment by phamquandung** [comment]
Dear mate. I was wondering if your code has evaluation part? I mean did you code the evaluation which compares to Euclidean and grid-based? Moreover, in your paper, I did not see the source of ground truth dataset you use to compare. Could you please tell me the source of ground truth? Thank you!

**Comment by niosus** [comment]
@phamquandung please don't start new threads inside other threads. If you have a new question, just open a new issue. The evaluation was relying on a multitude of scripts and has never matured to be open sourced unfortunately. I will not have the time to prepare the data and make is available unfortunately, sorry about that.
