### ISSUE TITLE
Basic theory discussion

### ISSUE THREAD

**Issue by lonlonago** [PRBonn/depth_clustering#43]
The difference in angle  BETA  between the two rays and the distance difference DELTA Depth  are actually the same thing. So what is the difference between the two? In addition, calculating the angle difference is actually more complicated than calculating the distance difference. Why choose a more complicated way? 

And why is your calculation method faster? Because the horizontal resolution is compressed to 870?

**Comment by niosus** [comment]
Answered in #44
