### ISSUE TITLE
Basic theory discussion

### ISSUE THREAD

**Issue by lonlonago** [PRBonn/depth_clustering#44]
Thanks for your work,  after I read the papers and code, I have some theoretical questions.

The difference in angle BETA between the two rays and the distance difference  Delta Depth are actually the same thing. So what is the difference between the two? In addition, calculating the angle difference is actually more complicated than calculating the distance difference. Why choose a more complicated way? 

And why is your calculation method faster? Because the horizontal resolution is compressed to 870?

Wait for your  reply!

**Comment by niosus** [comment]
> The difference in angle BETA between the two rays and the distance difference Delta Depth are actually the same thing.  

Not really. Think about thresholding these values. If you pick a threshold for the distance you will have to adapt it with the distance to the points you want to separate or merge. The angle BETA is not dependent on the absolute distance to the points.
