### ISSUE TITLE
Question about the implementation of the ground removal algorithm

### ISSUE THREAD

**Issue by MikeZhu92** [PRBonn/depth_clustering#46]
Hello!

Thank you for sharing the great package with really awesome features including the parameter tweaking.
I realized there was a parameter which might be quite important but not mentioned in the ground labeling algorithm part. 

Ref paper is `{Efficient Online Segmentation for Sparse 3D Laser Scans}`
On page 5: **Algorithm 1 Ground Labelling**

The first "pixel" enter into the `LABELGROUNDBFS`  will always be labelled as ground. `Line 10:      {r, c} ←labelled as ground`. (It's may or may not be true depends on the angle image and which colum the ground is at.)

I implemented the code myself and it seems that it will label most of the angle image as ground. So I checked the original implementation and found the parameter `Radians start_thresh = 30_deg;` in the `ZeroOutGroundBFS` function.

After adding this threshold, the result is much better. So I played with this parameter and realize  it will affect the algorithm a lot. If I set it to 10, then the result **with and without** the check `if |M(r, c) − M(rn, cn)| < 5◦ ` seems to be very similar. The data I'm using is HDL-64 S2.

Since you mentioned the radians start_thresh is optional in the code, I would like to double check with you and any further discussion would be great. my e-mail is: mike.driveai@gmail.com

Mike

**Comment by niosus** [comment]
@MikeZhu92 sorry for a huge delay. This is indeed a relatively important threshold to avoid labeling walls as ground. Without it we would assume every bottom-most pixel to be ground which is not true. There might be better way to deal with this, but for now I won't have the time to dive deeper into this.
