### ISSUE TITLE
‘CV_LOAD_IMAGE_ANYDEPTH’ was not declared in this scope

### ISSUE THREAD

**Issue by bsridatta** [PRBonn/depth_clustering#47]
opencv: '3.4.3'
Ubuntu: 18.04
ROS: Melodic

src/utils/velodyne_utils.cpp:111:42: error: ‘CV_LOAD_IMAGE_ANYDEPTH’ was not declared in this scope
   cv::Mat depth_image = cv::imread(path, CV_LOAD_IMAGE_ANYDEPTH);

Replacing it with the below works
`  cv::Mat depth_image = cv::imread(path, cv::IMREAD_ANYDEPTH);
`

**Comment by niosus** [comment]
Unfortunately, the code was written using opencv 2 and don't think I have the time to port it to opencv 3. Sorry about that.
