### ISSUE TITLE
Losing Intensity

### ISSUE THREAD

**Issue by strupy91** [PRBonn/depth_clustering#50]
Hello,
first of all, thanks for your awesome algorithm. Helped me a lot with my project. But is there any reason you did ignore the intensity of the pointcloud or there any version with it?

**Comment by niosus** [comment]
Hey! I never actually tried to run it with intensity as this is a purely geometric algorithm. But feel free to fork and extend if you have good ideas ;)

**Comment by niosus** [comment]
I will close this issue, but feel free to throw around some ideas here if you want.
