### ISSUE TITLE
Really bad visualization

### ISSUE THREAD

**Issue by yrt1993** [PRBonn/depth_clustering#52]
I don't know why the author show the segmentation result like this. When I run examples in the codes like show_objects_kitti and qt_gui_app, I see the original point cloud of white color with very many yellow or blue 3d bounding boxes and even more grey 3d bounding boxes. 

What I want to see is all those segmented object as well as the ground drawn with different colors and bounding boxes are dispensable. Then I get a visualized qualitative evaluation of the segmentation algorithm implemented in the depth-clustering 
![JD20191024141750](https://user-images.githubusercontent.com/39512783/67458586-25577b80-f669-11e9-9fc7-97281f7982b6.png)

**Comment by niosus** [comment]
The way your data is visualized looks weird. The vis in the readme is from the qt visualization, see the binaries provided. This will enable you to play with the parameters and hopefully improve the performance.

**Comment by niosus** [comment]
Closing for the lack of activity.
