### ISSUE TITLE
Depth Clustering for Merged Point Cloud 

### ISSUE THREAD

**Issue by ElifAksu** [PRBonn/depth_clustering#54]
Hi @niosus , thank you for your great work. I run depth clustering for VLP16 lidars and it works very well. I have a small question. i have two VLP16 lidar. i transformed on the same coordinates them and merged only their point clouds with the help of pcl_ros. I run the show_objects_node with the merged cloud topic.  However, depth clustering gives bad results on merged point cloud data and it seems ground remover does not work well because there are objects on the ground lines. 
Should i change any parameter to get better results, such as projection params?

**Comment by mainDevgithub** [comment]
> Hi [@niosus](https://github.com/niosus) , thank you for your great work. I run depth clustering for VLP16 lidars and it works very well. I have a small question. i have two VLP16 lidar. i transformed on the same coordinates them and merged only their point clouds with the help of pcl_ros. I run the show_objects_node with the merged cloud topic. However, depth clustering gives bad results on merged point cloud data and it seems ground remover does not work well because there are objects on the ground lines. Should i change any parameter to get better results, such as projection params?

Have you resolved this issue? My single VLP-16 also experiences ground line artifacts.
