### ISSUE TITLE
Segmentation fault running "show_objects_moosmann"

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [PRBonn/depth_clustering#56]
Data is at 
~/catkin_cluster/devel/lib/depth_clustering/data

When doing
~/catkin_cluster/devel/lib/depth_clustering$ ./show_objects_moosmann --path data/scenario1/

I get
Segmentation fault (core dumped)

My build results:
~/catkin_cluster$ catkin build depth_clustering

Profile:                     default
Extending:          [cached] /opt/ros/kinetic
Workspace:                   /home/mrt/catkin_cluster

Build Space:        [exists] /home/mrt/catkin_cluster/build
Devel Space:        [exists] /home/mrt/catkin_cluster/devel
Install Space:      [unused] /home/mrt/catkin_cluster/install
Log Space:          [exists] /home/mrt/catkin_cluster/logs
Source Space:       [exists] /home/mrt/catkin_cluster/src
DESTDIR:            [unused] None

Devel Space Layout:          linked
Install Space Layout:        None

Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False

Whitelisted Packages:        None
Blacklisted Packages:        None

Workspace configuration appears valid.

[build] Found '1' packages in 0.0 seconds.                                                                                                  
[build] Package table is up to date.                                                                                                        
Starting  >>> depth_clustering                                                                                                              
Finished  <<< depth_clustering                [ 0.4 seconds ]                                                                               
[build] Summary: All 1 packages succeeded!                                                                                                  
[build]   Ignored:   None.                                                                                                                  
[build]   Warnings:  None.                                                                                                                  
[build]   Abandoned: None.                                                                                                                  
[build]   Failed:    None.

**Comment by niosus** [comment]
Please provide a full path to the data. I don't think I made it possible to use the relative paths. Feel free to reopen if this does not help.
