### ISSUE TITLE
Stationary and Non Stationary objects 

### ISSUE THREAD

**Issue by abhigoku10** [PRBonn/depth_clustering#59]
@niosus @stachnis @ovysotska @tano297  Hi team thanks for sharing the code base , just wanted to  know if we can object segments of stationary objects like builidings lampost trees and non stationary objects from the  current code base, if so can you let us knw the process and the type of data since i want to try it other dataset and custom dataset !!!!!

**Comment by niosus** [comment]
This is not possible in this code. This code just performs the segmentation. You would need to write a tracker that would estimate if the clusters generated by this code represent a moving or a static object.
