### ISSUE TITLE
visualisation of clusters

### ISSUE THREAD

**Issue by bymbhaskar** [PRBonn/depth_clustering#63]
I am playing a bag file (Velodyne LiDAR 32 channel). Then I am running this command

rosrun depth_clustering show_objects_node

How to visualize the clusters using rviz?

**Comment by niosus** [comment]
You would need to write a node that publishes the clusters on some topic to visualize them in rviz. Currently, this is not implemented.

**Comment by bymbhaskar** [comment]
Is there any other way (using your program ) to visualize the cluster in real time (as shown in video)??
