### ISSUE TITLE
Can't achieve the same effect with my own data

### ISSUE THREAD

**Issue by GuoXiaoxiao1** [PRBonn/depth_clustering#70]
Hello, @niosus 
I'm sorry to disturb you. After reading your code, I have some questions to ask. 
First, when selecting different types of input files on the QT interface, although they are all 64 line data, the effects of KITTI bin files and scenario png files are very different. KITTI bin data results are obviously not good. Why is this?
Second, your paper said that it is also applicable to 16 line Lidar, but after I input the png files of 16 line Lidar, the segmentation effect is very poor and can hardly be used. Where is it that needs to be modified?

Looking forward to receiving your reply, thank you very much!

**Comment by niosus** [comment]
Without looking into your data, the only reason I can think if is that the angles between the beams are different for the different LiDARs. As for KITTI data, the actual data is pretty uncalibrated and does not produce nice range images, which is the reason for the failures that you see.
