### ISSUE TITLE
 Using two 16 line radar fusion data as input

### ISSUE THREAD

**Issue by GuoliangPeng** [PRBonn/depth_clustering#74]
Hello, I'm going to use the fusion data of two 16 line lidars as the input. How can I choose the program parameters?

**Comment by niosus** [comment]
The code in the repo is designed to work with a single LiDAR. This limitation is also described in the corresponding papers. The reason for this is that the points it would generate must fall exactly on the pixels of the range image. You can try to project the fused point cloud onto a custom range image but this is prone to failure as there will be gaps in the range data. If you manage to create a range image without the gaps from your fused LiDAR setup the algorithm should work.
